name: 'intercom_source' #this should be the name of the connector
version: '0.1.0' #This should align w/ the current release version
config-version: 2 #Required dbt config

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

#Model materialization should be defined as below
models: 
  intercom_source:
    materialized: table
    tmp:
      materialized: view

#Any variable used in models should be explicitly defined in the model file.
#All variables used should always have a default model. Variables used should be outlined in the README
vars:
  intercom_source:
    admin: "{{ source('intercom_development','admin') }}"
    #tag: "{{ source('intercom_development','tag') }}"
    conversation_history: "{{ source('intercom_development','conversation_history') }}"
    conversation_part_history: "{{ source('intercom_development','conversation_part_history') }}"
    contact_history: "{{ source('intercom_development','contact_history') }}"
    #contact_tag_history: "{{ source('intercom_development','contact_tag_history') }}"
    conversation_contact_history: "{{ source('intercom_development','conversation_contact_history') }}"
    company_history: "{{ source('intercom_development','company_history') }}"
    #company_tag_history: "{{ source('intercom_development','company_tag_history') }}"
    contact_company_history: "{{ source('intercom_development','contact_company_history') }}"

    #(Optional) Pass-through arrays.
    admin_pass_through_columns: []
    conversation_history_pass_through_columns: []
    conversation_part_history_pass_through_columns: []
    contact_history_pass_through_columns: []
    contact_history_pass_through_columns: []


